### ISSUE TITLE
图片的暗黑处理还是出不来, 依然是light模式下的图片填充

### ISSUE THREAD

**Issue by snaillovesmile** [Elenionl/EasyDarkMode#1]

**Comment by snaillovesmile** [comment]
不知道为什么, demo可以, 我的工程就是不行...醉了哈哈

**Comment by Elenionl** [comment]
能把你具体调用了哪个方法发一下看看么？
你的图片是来源于本地图片还是网络图片？

**Comment by Elenionl** [comment]
@SnailLoveSmile 你好
能把你具体调用了哪个方法发一下看看么？
你的图片是来源于本地图片还是网络图片？

**Comment by snaillovesmile** [comment]
图片是本地图片, light的是Images.xcassets里面的, dark的是Images.xcassets中另一张, 调用方法是dm_image的方法

**Comment by Elenionl** [comment]
Problem fixed. Have another try with version 2.0.5.
