### ISSUE TITLE
Kingfisher deployment target

### ISSUE THREAD

**Issue by Maxatma** [Elenionl/EasyDarkMode#3]
Hi, would be nice to update to the latest Kingfisher, if possible 

EasyDarkMode has 
  s.platform     = :ios, "8.0"
but latests Kingfisher
  s.ios.deployment_target = "10.0"

and connectWithKingfisher method will be needed to update.
Thanks :)

**Comment by Elenionl** [comment]
Please try using version 4.0.1
Deploy target has been change to 10.0
